name: Test on Ubuntu
on:
  push:
    branch: [main]
    tags: ['v*']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09:/home/runner/.nix-defexpr/channels
      - name: Add Home Manager
        run: nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
      - name: Update channels
        run: nix-channel --update
      - name: Install Home Manager
        run: nix-shell '<home-manager>' -A install
      - name: Switch with default config
        run: home-manager switch
      - name: Rebuild Home Manager
        run: make _setup
